# Generated by Django 4.0.3 on 2022-03-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='issue',
        ),
    ]
