# Generated by Django 4.0.3 on 2022-03-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='project',
            new_name='project_id',
        ),
    ]
