# Generated by Django 4.0.3 on 2022-03-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_issue_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50),
        ),
    ]
