# Generated by Django 4.0.3 on 2022-03-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_user',
            new_name='author_user_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='issue',
            new_name='issue_id',
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BE', 'BACK-END'), ('FE', 'FRONT-END'), ('IOS', 'iOS'), ('AND', 'ANDROID')], max_length=50),
        ),
    ]
