# Generated by Django 4.0.3 on 2022-03-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_author_user_comment_author_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'FAIBLE'), ('MED', 'MOYENNE'), ('HIGH', 'ELEVEE')], default='LOW', max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'A FAIRE'), ('CURR', 'EN COURS'), ('DONE', 'TERMINE')], default='TODO', max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'BUG'), ('UPD', 'AMELIORATION'), ('TASK', 'TÂCHE')], default='BUG', max_length=50),
        ),
    ]
